baseURL = 'https://bhumish.github.io/'
languageCode = 'en-us'
title = "Bhumish's Blog"
theme = 'PaperMod'
enableRobotsTXT = true

[minify]
disableXML = true
minifyOutput = true

[params]
headTitle = "Bhumish's Blog 🌎"
title = "Bhumish's Blog 🌎"
description = "My journal where I write mostly about Information Security, and sometimes I try to fit in a few personal achievements and travel stories."
defaultTheme = "light"
disableThemeToggle = false


# Social links
github = "bhumish"
twitter = "bhumish"
email = "bhumish@live.com"

# Optional settings
dateFormat = "2006-Jan-02"
showWordCount = false
showReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
disableScrollToTop = false
hidemeta = false
hideSummary = false
  
[params.assets]
# disableHLJS = true # to disable highlight.js
# disableFingerprinting = true
favicon = "/favicon.ico"
favicon16x16 = "/favicon-16x16.png"
favicon32x32 = "/favicon-32x32.png"
apple_touch_icon = "/apple-touch-icon.png"

[params.label]
text = "Bhumish's Blog 🎉🌎"
icon = "/apple-touch-icon.png"
iconHeight = 35

# profile-mode
[params.profileMode]
enabled = true # needs to be explicitly set
title = "Bhumish Gajjar"
subtitle = "Information Security enthusiast, works in Security Engineering, VA-PT, Threat Hunting, Cloud Security and Vulnerability Management."
imageUrl = "images/profile.jpg"
imageWidth = 120
imageHeight = 120
#imageTitle = "my image"

[[params.profileMode.buttons]]
name = "Posts"
url = "posts"

[[params.profileMode.buttons]]
name = "About Me"
url = "about-me"

# home-info mode
[params.homeInfoParams]
Title = "Aloha! 👋"
Content = "This is my journal where I write mostly about Information Security and Tech, and sometimes I try to fit in a few personal achievements and travel stories. "

[[params.socialIcons]]
name = "linkedin"
url = "https://linkedin.com/in/bhumish/"

[[params.socialIcons]]
name = "x"
url = "https://x.com/bhumish"

[[params.socialIcons]]
name = "wordpress"
url = "https://bhumishgajjar.wordpress.com/"

[[params.socialIcons]]
name = "instagram"
url = "https://bhumish.github.io/posts/i-am-not-on-instagram"

[params.cover]
hidden = true # hide everywhere but not in structured data
hiddenInList = true # hide on list pages and home
hiddenInSingle = true # hide on single page


# for search
# https://fusejs.io/api/options.html
[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
limit = 10 # refer: https://www.fusejs.io/api/methods.html#search
keys = ["title", "permalink", "summary", "content"]

[[menu.main]]
identifier = "about-me"
name = "about-me"
url = "/about-me/"
weight = 20

[[menu.main]]
identifier = "posts"
name = "posts"
url = "/posts/"
weight = 10

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
[markup.highlight]
noClasses = false
# anchorLineNos = true
# codeFences = true
# guessSyntax = true
# lineNos = true
# style = "monokai"
